### ISSUE TITLE
想问一下模型训练需要多少条样本

### ISSUE THREAD

**Issue by yuqinyuqinyuqin** [shibing624/wordrank#1]
### Describe the Question
Please provide a clear and concise description of what the question is.

### Describe your attempts
- [ ] I walked through the tutorials
- [ ] I checked the documentation
- [ ] I checked to make sure that this is not a duplicate question

**Comment by shibing624** [comment]
1. 分类任务（包括rank任务）标注数据是垂直领域适用的，可以用开放比赛标注过的数据；
2. 样本集大小依赖任务难度和模型复杂度而定，如果是机器学习模型每个标签样本量2000左右，深度模型需要更多上万条比较好。

**Comment by yuqinyuqinyuqin** [comment]
谢谢大佬细致的回答，十分感激！我看到在您的数据上有一些类标为5和6的，好像不在 可省略词，限定词，核心词，干扰词 这四大类中，我猜测是自己业务数据上特别重要的词，需要单独拎出来嘛？希望得到您的解答！感恩



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xuming ***@***.***&gt;
发送时间: 2021年7月22日 16:48
收件人: shibing624/wordrank ***@***.***&gt;
抄送: 打了鸡血的女汉子 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[shibing624/wordrank] 想问一下模型训练需要多少条样本 (#1)





  
分类任务（包括rank任务）标注数据是垂直领域适用的，可以用开放比赛标注过的数据； 

样本集大小依赖任务难度和模型复杂度而定，如果是机器学习模型每个标签样本量2000左右，深度模型需要更多上万条比较好。
